gcc -march=native -O3 -std=c++17 -DNSYS=2 -DBSM -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o bsm_2.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=2 -DBOSE_QUAD -DNORMAL -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o bose_quad_2.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=4 -DSPARSE -DFERMI_LINEAR -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_omp_thermo.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o thermo_fermi_2.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=2 -DBOSE_QUAD -DNORMAL -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_omp_thermo.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o thermo_bose_quad_2.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=4 -DFERMI_QUAD -DSPARSE -DNORMAL -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o fermi_quad_4.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=2 -DFERMI_QUAD -DSPARSE -DNORMAL -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o fermi_quad_2.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=2 -DBOSE_LINEAR -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o bose_2.out
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=4 -DSPARSE -DFERMI_LINEAR -DNORMAL -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o fermi_4.out;
# # #
gcc -march=native -O3 -std=c++17 -DNSYS=4 -DSPARSE -DTEMPLATE -DNORMAL -Wall -Iinclude -I/usr/local/include/eigen3 -I/usr/local/include/tsl -funroll-loops -funroll-loops main_threads_omp_equ_corr.cpp -Wl,--start-group -lstdc++ -lm -ldl -pthread -l:liblzma.a -l:libglog.a -l:libgflags.a -ldl -pthread -l:libdouble-conversion.a -l:libunwind.a -l:libfolly.a -l:libfmt.a -l:libjson11.a -fopenmp -fPIE -Wl,--end-group -o template.out;